global:
  scrape_interval: 10s

scrape_configs:
  - job_name: traefik
    static_configs:
      - targets:
          - traefik:8082
  - job_name: node-exporter
    static_configs:
      - targets:
        - node-exporter:9100
  - job_name: victoria-metrics
    static_configs:
      - targets:
          - victoria-metrics:8428
  - job_name: vmagent
    static_configs:
      - targets:
        - vmagent:8429
  - job_name: tempo
    static_configs:
      - targets:
          - tempo:3200
  - job_name: grafana
    static_configs:
      - targets:
          - grafana:3000