{
 "title": "Grafana",
 "description": "Grafana Internal Metics Dashboards",
 "tags": [ "grafana" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(grafana_instance_start_total, job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "General Counters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "description": "start time of the process",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{job=\"$job\"} * 1000"
    }
   ]
  },
  {
   "title": "Organisation Count",
   "type": "stat",
   "description": "total amount of orgs",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "grafana_stat_total_orgs{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "User Count",
   "type": "stat",
   "description": "total amount of users",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "grafana_stat_total_users{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Dashboard Count",
   "type": "stat",
   "description": "total amount of dashboards",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "grafana_stat_totals_dashboard{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "CPU, Memory and File Descriptor Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Average CPU Usage",
   "type": "graph",
   "description": "Average user and system CPU time spent in seconds.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total{job=\"$job\"}[5m]))",
     "legendFormat": "CPU Time"
    }
   ]
  },
  {
   "title": "Average Memory Usage",
   "type": "graph",
   "description": "Virtual and Resident memory size in bytes, averages over 5 min interval",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(rate(process_resident_memory_bytes{job=\"$job\"}[5m]))",
     "legendFormat": "Resident Mem"
    },
    {
     "expr": "avg(rate(process_virtual_memory_bytes{job=\"$job\"}[5m]))",
     "legendFormat": "Virtual Mem"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "graph",
   "description": "Number of open file descriptors",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{job=\"$job\"}",
     "legendFormat": "Open FD"
    }
   ]
  },
  {
   "title": "Responce Codes and Logins",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total Response Statuses",
     "type": "graph",
     "description": "http response status",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "grafana_api_response_status_total{job=\"$job\"}",
       "legendFormat": "API {{ code }}"
      },
      {
       "expr": "grafana_page_response_status_total{job=\"$job\"}",
       "legendFormat": "Page {{ code }}"
      },
      {
       "expr": "grafana_proxy_response_status_total{job=\"$job\"}",
       "legendFormat": "Proxy {{ code }}"
      }
     ]
    },
    {
     "title": "HTTP Req/Resp Details",
     "type": "graph",
     "description": "http request counter",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "grafana_datasource_request_total{job=\"$job\"}",
       "legendFormat": "{{handler}} - {{method}} - {{statuscode}}"
      }
     ]
    },
    {
     "title": "Login Counts",
     "type": "graph",
     "description": "api login counters",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "grafana_api_login_post_total{job=\"$job\"}",
       "legendFormat": "POST"
      },
      {
       "expr": "grafana_api_login_oauth_total{job=\"$job\"}",
       "legendFormat": "OAuth"
      }
     ]
    }
   ]
  },
  {
   "title": "Dataproxy Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Dataproxy Request Quantiles",
     "type": "graph",
     "description": "summary for dataproxy request duration",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "grafana_api_dataproxy_request_all_milliseconds{job=\"$job\", quantile=\"0.5\"}",
       "legendFormat": "0.5 "
      },
      {
       "expr": "grafana_api_dataproxy_request_all_milliseconds{job=\"$job\", quantile=\"0.9\"}",
       "legendFormat": "0.9"
      },
      {
       "expr": "grafana_api_dataproxy_request_all_milliseconds{job=\"$job\", quantile=\"0.99\"}",
       "legendFormat": "0.99"
      }
     ]
    },
    {
     "title": "Dataproxy Request Avg [5 min]",
     "type": "graph",
     "description": "average dataproxy request duration over 5 minutes",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "rate(grafana_api_dataproxy_request_all_milliseconds_sum{job=\"$job\"}[5m]) / rate(grafana_api_dataproxy_request_all_milliseconds_count{job=\"$job\"}[5m])",
       "legendFormat": "Average Requests Duration"
      }
     ]
    }
   ]
  },
  {
   "title": "Dashboard Get Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Dashboard Get Duration Quantiles",
     "type": "graph",
     "description": "summary for dashboard get duration",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "grafana_api_dashboard_get_milliseconds{job=\"$job\", quantile=\"0.5\"}",
       "legendFormat": "0.5"
      },
      {
       "expr": "grafana_api_dashboard_get_milliseconds{job=\"$job\", quantile=\"0.9\"}",
       "legendFormat": "0.9"
      },
      {
       "expr": "grafana_api_dashboard_get_milliseconds{job=\"$job\", quantile=\"0.99\"}",
       "legendFormat": "0.99"
      }
     ]
    },
    {
     "title": "Dashboard Get Duration Avg [5 min]",
     "type": "graph",
     "description": "average dashboard get duration over 5 minutes",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "rate(grafana_api_dashboard_get_milliseconds_sum{job=\"$job\"}[5m]) / rate(grafana_api_dashboard_get_milliseconds_count{job=\"$job\"}[5m])",
       "legendFormat": "0.5"
      }
     ]
    }
   ]
  },
  {
   "title": "Dashboard Save Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Dashboard Save Duration Quantiles",
     "type": "graph",
     "description": "summary for dashboard save duration",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "grafana_api_dashboard_save_milliseconds{job=\"$job\", quantile=\"0.5\"}",
       "legendFormat": "0.5"
      },
      {
       "expr": "grafana_api_dashboard_save_milliseconds{job=\"$job\", quantile=\"0.9\"}",
       "legendFormat": "0.9"
      },
      {
       "expr": "grafana_api_dashboard_save_milliseconds{job=\"$job\", quantile=\"0.99\"}",
       "legendFormat": "0.99"
      }
     ]
    },
    {
     "title": "Dashboard Save Duration Avg [5 min]",
     "type": "graph",
     "description": "average dashboard save duration over 5 minutes",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "rate(grafana_api_dashboard_save_milliseconds_sum{job=\"$job\"}[5m]) / rate(grafana_api_dashboard_save_milliseconds_count{job=\"$job\"}[5m])",
       "legendFormat": "0.5"
      }
     ]
    }
   ]
  },
  {
   "title": "Dashboard Search Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Dashboard Search Duration Quantiles",
     "type": "graph",
     "description": "summary for dashboard search duration",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "grafana_api_dashboard_search_milliseconds{job=\"$job\", quantile=\"0.5\"}",
       "legendFormat": "0.5"
      },
      {
       "expr": "grafana_api_dashboard_search_milliseconds{job=\"$job\", quantile=\"0.9\"}",
       "legendFormat": "0.9"
      },
      {
       "expr": "grafana_api_dashboard_search_milliseconds{job=\"$job\", quantile=\"0.99\"}",
       "legendFormat": "0.99"
      }
     ]
    },
    {
     "title": "Dashboard Search Duration Avg [5 min]",
     "type": "graph",
     "description": "average dashboard search duration over 5 minutes",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "rate(grafana_api_dashboard_search_milliseconds_sum{job=\"$job\"}[5m]) / rate(grafana_api_dashboard_search_milliseconds_count{job=\"$job\"}[5m])",
       "legendFormat": "0.5"
      }
     ]
    }
   ]
  }
 ]
}